stages:
  - build
  - scan
  - docker_build
  - image_scan
  - docker_push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: roxilius17/anime-fe

before_script:
  - echo "🚀 Start CI/CD pipeline"

build_app:
  stage: build
  image: node:20-alpine
  script:
    - corepack enable && corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile || pnpm install --force
    - pnpm run build
  artifacts:
    paths:
      - dist

trivy_fs_scan:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL .

docker_build:
  stage: docker_build
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - docker build --pull --no-cache -t $IMAGE_NAME:latest .
    - docker save -o docker-image.tar $IMAGE_NAME:latest
  artifacts:
    paths:
      - docker-image.tar
    expire_in: 1h

trivy_image_scan:
  stage: image_scan
  needs: ["docker_build"]
  image: docker:24.0.5
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
    - mv ./bin/trivy /usr/local/bin/trivy
  script:
    - docker load -i docker-image.tar
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME:latest

docker_push:
  stage: docker_push
  needs: ["trivy_image_scan"]
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker load -i docker-image.tar
    - docker push $IMAGE_NAME:latest
