stages:
  - build
  - scan
  - docker

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: roxilius17/anime-fe

before_script:
  - echo "🚀 Start CI/CD pipeline"

# =====================
# Build App (opsional kalau masih ada proses build FE)
# =====================
build_app:
  stage: build
  image: node:20-alpine
  script:
    - corepack enable && corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile || pnpm install --force
    - pnpm run build
  artifacts:
    paths:
      - dist

# =====================
# Trivy Filesystem Scan
# =====================
trivy_fs_scan:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    # Scan source code
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL .

# =====================
# Docker Build & Push
# =====================
docker_build:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  artifacts:
    name: "docker-image"
    expire_in: 1h
    paths:
      - .

# =====================
# Trivy Docker Image Scan
# =====================
trivy_image_scan:
  stage: scan
  needs: ["docker_build"]   # pastikan jalan setelah docker_build
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    # Scan image yang baru dibuild
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME:latest
